import AudiA4Luxury from "../assets/AudiA4-Luxury-(gray).png";
import BMW3Series from "../assets/BMW-3-Series-Luxury(silver).png";
import ChevroletMalibu from "../assets/Chevrolet Malibu-Sedan(white).png";
import ChevroletSilverado from "../assets/Chevrolet-Silverado-Truck(red).png";
import ChevroletTraverse from "../assets/Chevrolet-Traverse-SUV(red).png";
import FordMustang from "../assets/Ford Mustang-Sports Car(red).png";
import FordExplorer from "../assets/Ford-Explorer-SUV(white).png";
import FordF150 from "../assets/Ford-F-150-Truck(silver).png";
import GMCSierra from "../assets/GMC-Sierra-Truck(blue).png";
import HondaCivic from "../assets/Honda-Civic-Sedan(blue).png";
import HondaOdyssey from "../assets/Honda-Odyssey-Minivan(white).png";
import JeepWrangler from "../assets/Jeep-Wrangler-SUV(Green).png";
import KiaSportage from "../assets/Kia-Sportage-SUV(black).png";
import MazdaCX5 from "../assets/Mazda-CX-5-SUV(gray).png";
import MercedesBenz from "../assets/Mercedes-Benz C-Class-Luxury(black).png";
import NissanTitan from "../assets/Nissan-Titan-Truck(gray).png";
import NissanAltima from "../assets/NissanAltima-Sedan(black).jpg";
import Ram1500 from "../assets/Ram-1500-Truck(black).png";
import SubaruOutback from "../assets/Subaru-Outback-Wagon(blue).png";
import TeslaModel3 from "../assets/TeslaModel3-electric(blue).png";
import ToyotaCamry from "../assets/Toyota Camry-Sedan(silver).png";
import ToyotaRAV4 from "../assets/Toyota-RAV4-SUV(blue).png";
import Volkswagen from "../assets/Volkswagen-Golf-SportWagen-Wagon(white).png";
import VolvoV60 from "../assets/Volvo-V60-Wagon(blue).png";
import HyundaiTucson from "../assets/Hyundai-Tucson-SUV(siver).png";

const Cars = [
  {
    id: 1,
    model: "Toyota Camry",
    category: "Sedan",
    color: "Silver",
    price: 25000,
    company: "Toyota",
    image: ToyotaCamry,
    seats: 5,
    transmission: "Automatic" as const,
    fuelType: "Gasoline" as const,
    year: 2024,
    mileage: "New",
    description: "The Toyota Camry delivers exceptional reliability and comfort. With its refined interior, advanced safety features, and efficient engine, it's the perfect family sedan for everyday commutes and long road trips alike.",
  },
  {
    id: 2,
    model: "Honda Civic",
    category: "Sedan",
    color: "Blue",
    price: 22000,
    company: "Honda",
    image: HondaCivic,
    seats: 5,
    transmission: "Automatic" as const,
    fuelType: "Gasoline" as const,
    year: 2024,
    mileage: "New",
    description: "The Honda Civic combines sporty styling with practical efficiency. Known for its legendary reliability, responsive handling, and fuel-efficient engine, it's an excellent choice for drivers who want both fun and practicality.",
  },
  {
    id: 3,
    model: "Ford Mustang",
    category: "Sports Car",
    color: "Red",
    price: 35000,
    company: "Ford",
    image: FordMustang,
    seats: 4,
    transmission: "Manual" as const,
    fuelType: "Gasoline" as const,
    year: 2024,
    mileage: "New",
    description: "An American icon, the Ford Mustang delivers thrilling performance and head-turning style. With its powerful V8 engine option, aggressive stance, and driver-focused cockpit, it's pure muscle car excitement.",
  },
  {
    id: 4,
    model: "Chevrolet Malibu",
    category: "Sedan",
    color: "White",
    price: 28000,
    company: "Chevrolet",
    image: ChevroletMalibu,
    seats: 5,
    transmission: "Automatic" as const,
    fuelType: "Gasoline" as const,
    year: 2024,
    mileage: "New",
    description: "The Chevrolet Malibu offers a smooth ride with a spacious interior. Its modern infotainment system, comfortable seating, and efficient turbocharged engine make it a compelling choice in the midsize sedan segment.",
  },
  {
    id: 5,
    model: "Nissan Altima",
    category: "Sedan",
    color: "Black",
    price: 23000,
    company: "Nissan",
    image: NissanAltima,
    seats: 5,
    transmission: "Automatic" as const,
    fuelType: "Gasoline" as const,
    year: 2023,
    mileage: "12,000 mi",
    description: "The Nissan Altima features available all-wheel drive and a comfortable, well-appointed interior. With its striking design and advanced driver assistance features, it stands out in the competitive sedan market.",
  },
  {
    id: 6,
    model: "Tesla Model 3",
    category: "Electric",
    color: "Blue",
    price: 50000,
    company: "Tesla",
    image: TeslaModel3,
    seats: 5,
    transmission: "Automatic" as const,
    fuelType: "Electric" as const,
    year: 2024,
    mileage: "New",
    description: "The Tesla Model 3 revolutionizes electric driving with instant acceleration, cutting-edge technology, and impressive range. Its minimalist interior and Autopilot capabilities represent the future of automotive innovation.",
  },
  {
    id: 7,
    model: "BMW 3 Series",
    category: "Luxury",
    color: "Silver",
    price: 45000,
    company: "BMW",
    image: BMW3Series,
    seats: 5,
    transmission: "Automatic" as const,
    fuelType: "Gasoline" as const,
    year: 2024,
    mileage: "New",
    description: "The BMW 3 Series sets the benchmark for sport sedans. With its perfect 50/50 weight distribution, powerful engine options, and luxurious cabin, it delivers the ultimate driving experience in its class.",
  },
  {
    id: 8,
    model: "Audi A4",
    category: "Luxury",
    color: "Gray",
    price: 48000,
    company: "Audi",
    image: AudiA4Luxury,
    seats: 5,
    transmission: "Automatic" as const,
    fuelType: "Gasoline" as const,
    year: 2024,
    mileage: "New",
    description: "The Audi A4 combines quattro all-wheel drive with sophisticated German engineering. Its refined interior, advanced virtual cockpit, and smooth ride quality make it a top contender in the luxury sedan segment.",
  },
  {
    id: 9,
    model: "Mercedes-Benz C-Class",
    category: "Luxury",
    color: "Black",
    price: 52000,
    company: "Mercedes-Benz",
    image: MercedesBenz,
    seats: 5,
    transmission: "Automatic" as const,
    fuelType: "Gasoline" as const,
    year: 2024,
    mileage: "New",
    description: "The Mercedes-Benz C-Class epitomizes luxury and prestige. With its elegant design, cutting-edge MBUX infotainment system, and silky-smooth ride, it delivers first-class comfort in a compact package.",
  },
  {
    id: 10,
    model: "Jeep Wrangler",
    category: "SUV",
    color: "Green",
    price: 35000,
    company: "Jeep",
    image: JeepWrangler,
    seats: 5,
    transmission: "Manual" as const,
    fuelType: "Gasoline" as const,
    year: 2024,
    mileage: "New",
    description: "The Jeep Wrangler is the ultimate off-road adventure vehicle. With its legendary 4x4 capability, removable doors and roof, and rugged durability, it's built for those who crave exploration and freedom.",
  },
  {
    id: 11,
    model: "Ford Explorer",
    category: "SUV",
    color: "White",
    price: 40000,
    company: "Ford",
    image: FordExplorer,
    seats: 7,
    transmission: "Automatic" as const,
    fuelType: "Gasoline" as const,
    year: 2024,
    mileage: "New",
    description: "The Ford Explorer offers three rows of seating and impressive capability. Its powerful engine options, advanced safety features, and spacious cargo area make it perfect for families on the go.",
  },
  {
    id: 12,
    model: "Toyota RAV4",
    category: "SUV",
    color: "Blue",
    price: 32000,
    company: "Toyota",
    image: ToyotaRAV4,
    seats: 5,
    transmission: "Automatic" as const,
    fuelType: "Hybrid" as const,
    year: 2024,
    mileage: "New",
    description: "The Toyota RAV4 combines rugged styling with exceptional practicality. Available in hybrid form for maximum efficiency, it offers a comfortable ride, ample cargo space, and Toyota's renowned reliability.",
  },
  {
    id: 13,
    model: "Chevrolet Traverse",
    category: "SUV",
    color: "Red",
    price: 38000,
    company: "Chevrolet",
    image: ChevroletTraverse,
    seats: 8,
    transmission: "Automatic" as const,
    fuelType: "Gasoline" as const,
    year: 2024,
    mileage: "New",
    description: "The Chevrolet Traverse provides maximum space for the whole family. With seating for up to 8, a smooth V6 engine, and an intuitive infotainment system, it's built for comfortable family adventures.",
  },
  {
    id: 14,
    model: "Hyundai Tucson",
    category: "SUV",
    color: "Silver",
    price: 28000,
    company: "Hyundai",
    image: HyundaiTucson,
    seats: 5,
    transmission: "Automatic" as const,
    fuelType: "Hybrid" as const,
    year: 2024,
    mileage: "New",
    description: "The Hyundai Tucson features striking design and excellent value. With its hybrid powertrain option, comprehensive warranty, and modern technology, it punches well above its weight class.",
  },
  {
    id: 15,
    model: "Kia Sportage",
    category: "SUV",
    color: "Black",
    price: 30000,
    company: "Kia",
    image: KiaSportage,
    seats: 5,
    transmission: "Automatic" as const,
    fuelType: "Gasoline" as const,
    year: 2024,
    mileage: "New",
    description: "The Kia Sportage impresses with bold styling and premium features. Its dual-screen dashboard, comfortable interior, and long warranty make it a smart choice for value-conscious buyers.",
  },
  {
    id: 16,
    model: "Mazda CX-5",
    category: "SUV",
    color: "Gray",
    price: 29000,
    company: "Mazda",
    image: MazdaCX5,
    seats: 5,
    transmission: "Automatic" as const,
    fuelType: "Gasoline" as const,
    year: 2024,
    mileage: "New",
    description: "The Mazda CX-5 delivers premium feel at a mainstream price. With its upscale interior, engaging driving dynamics, and elegant Kodo design language, it's the driver's choice among compact SUVs.",
  },
  {
    id: 17,
    model: "Subaru Outback",
    category: "Wagon",
    color: "Blue",
    price: 33000,
    company: "Subaru",
    image: SubaruOutback,
    seats: 5,
    transmission: "Automatic" as const,
    fuelType: "Gasoline" as const,
    year: 2024,
    mileage: "New",
    description: "The Subaru Outback combines wagon versatility with SUV capability. Standard all-wheel drive, generous ground clearance, and a rugged attitude make it perfect for outdoor enthusiasts.",
  },
  {
    id: 18,
    model: "Volkswagen Golf SportWagen",
    category: "Wagon",
    color: "White",
    price: 31000,
    company: "Volkswagen",
    image: Volkswagen,
    seats: 5,
    transmission: "Automatic" as const,
    fuelType: "Gasoline" as const,
    year: 2023,
    mileage: "8,500 mi",
    description: "The Volkswagen Golf SportWagen offers European refinement and practicality. Its turbocharged engine, precise handling, and expansive cargo area make it ideal for those who appreciate driving dynamics.",
  },
  {
    id: 19,
    model: "Volvo V60",
    category: "Wagon",
    color: "Blue",
    price: 36000,
    company: "Volvo",
    image: VolvoV60,
    seats: 5,
    transmission: "Automatic" as const,
    fuelType: "Hybrid" as const,
    year: 2024,
    mileage: "New",
    description: "The Volvo V60 represents Scandinavian luxury at its finest. With world-class safety features, a serene interior, and available plug-in hybrid powertrain, it's the sophisticated wagon choice.",
  },
  {
    id: 20,
    model: "Ford F-150",
    category: "Truck",
    color: "Silver",
    price: 40000,
    company: "Ford",
    image: FordF150,
    seats: 5,
    transmission: "Automatic" as const,
    fuelType: "Gasoline" as const,
    year: 2024,
    mileage: "New",
    description: "America's best-selling truck, the Ford F-150 delivers legendary capability. With its aluminum body, powerful engine options, and innovative features like Pro Power Onboard, it's built Ford tough.",
  },
  {
    id: 21,
    model: "Chevrolet Silverado",
    category: "Truck",
    color: "Red",
    price: 42000,
    company: "Chevrolet",
    image: ChevroletSilverado,
    seats: 5,
    transmission: "Automatic" as const,
    fuelType: "Gasoline" as const,
    year: 2024,
    mileage: "New",
    description: "The Chevrolet Silverado combines brawn with refinement. Its spacious cabin, impressive towing capacity, and available Multi-Flex tailgate make it a versatile workhorse for any job.",
  },
  {
    id: 22,
    model: "Ram 1500",
    category: "Truck",
    color: "Black",
    price: 45000,
    company: "Ram",
    image: Ram1500,
    seats: 5,
    transmission: "Automatic" as const,
    fuelType: "Gasoline" as const,
    year: 2024,
    mileage: "New",
    description: "The Ram 1500 sets the standard for truck luxury. With its coil-spring rear suspension, premium interior materials, and smooth ride quality, it proves trucks can be refined and capable.",
  },
  {
    id: 23,
    model: "GMC Sierra",
    category: "Truck",
    color: "Blue",
    price: 47000,
    company: "GMC",
    image: GMCSierra,
    seats: 5,
    transmission: "Automatic" as const,
    fuelType: "Gasoline" as const,
    year: 2024,
    mileage: "New",
    description: "The GMC Sierra delivers professional-grade capability with premium touches. Its MultiPro tailgate, CarbonPro bed option, and refined cabin make it the choice for discerning truck buyers.",
  },
  {
    id: 24,
    model: "Nissan Titan",
    category: "Truck",
    color: "Gray",
    price: 43000,
    company: "Nissan",
    image: NissanTitan,
    seats: 5,
    transmission: "Automatic" as const,
    fuelType: "Gasoline" as const,
    year: 2023,
    mileage: "15,000 mi",
    description: "The Nissan Titan offers a powerful V8 engine and straightforward truck experience. With its comfortable cabin, strong towing capability, and competitive pricing, it's a solid full-size choice.",
  },
  {
    id: 25,
    model: "Honda Odyssey",
    category: "Minivan",
    color: "White",
    price: 35000,
    company: "Honda",
    image: HondaOdyssey,
    seats: 8,
    transmission: "Automatic" as const,
    fuelType: "Gasoline" as const,
    year: 2024,
    mileage: "New",
    description: "The Honda Odyssey is the ultimate family hauler. With its versatile Magic Slide second-row seats, built-in vacuum cleaner, and rear entertainment system, it makes family travel a breeze.",
  },
];

export default Cars;
